// GENERATED by tool/fetch_festival_images.ps1 - do not edit by hand.
//
// Every photograph below is a real, freely licensed image of the festival it is
// attached to, downloaded from Wikimedia Commons. Festivals with no suitable
// photograph are deliberately left without one so the UI shows its own icon
// instead of an unrelated picture.
class FestivalImageCredit {
  const FestivalImageCredit({
    required this.assetPath,
    required this.author,
    required this.license,
    required this.source,
  });

  final String assetPath;
  final String author;
  final String license;
  final String source;
}

const Map<String, FestivalImageCredit> festivalImageCredits =
    <String, FestivalImageCredit>{
  'buddha-jayanti': FestivalImageCredit(
    assetPath: 'assets/images/festivals/buddha-jayanti.jpg',
    author: 'Bijaya2043',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Buddha Jayanti-IMG 9085.jpg',
  ),
  'janai-purnima': FestivalImageCredit(
    assetPath: 'assets/images/festivals/janai-purnima.jpg',
    author: 'Perrine Aguiar',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Boys ablution Janai Purnima.jpg',
  ),
  'vijaya-dashami': FestivalImageCredit(
    assetPath: 'assets/images/festivals/vijaya-dashami.jpg',
    author: 'Safalphotos',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Soaring High in Dashain.jpg',
  ),
  'laxmi-puja': FestivalImageCredit(
    assetPath: 'assets/images/festivals/laxmi-puja.jpg',
    author: 'Gaurav Dhwaj Khadka',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Laxmi Puja.jpg',
  ),
  'kukur-tihar': FestivalImageCredit(
    assetPath: 'assets/images/festivals/kukur-tihar.jpg',
    author: 'Manto17',
    license: 'CC0',
    source: 'Wikimedia Commons: File:Kukur Tihar or Dog Puja in Kathmandu. Dog decorate with marigold garland and Tika.jpg',
  ),
  'bhai-tika': FestivalImageCredit(
    assetPath: 'assets/images/festivals/bhai-tika.jpg',
    author: 'Toshiro lama',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Bhai Tika, Bhai Tika.jpg',
  ),
  'chhath': FestivalImageCredit(
    assetPath: 'assets/images/festivals/chhath.jpg',
    author: 'Bijay Chaurasia',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Chhath festival in Nepal-070A2127.jpg',
  ),
  'holi': FestivalImageCredit(
    assetPath: 'assets/images/festivals/holi.jpg',
    author: 'Bijay Chaurasia',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Holi festival celebration in Kathmandu 2025-070A3156.jpg',
  ),
  'nepali-new-year': FestivalImageCredit(
    assetPath: 'assets/images/festivals/nepali-new-year.jpg',
    author: 'Nrik kiran',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Bisket Jatra festival 2018 at the Nyatapola temple, Bhaktapur.jpg',
  ),
  'constitution-day': FestivalImageCredit(
    assetPath: 'assets/images/festivals/constitution-day.jpg',
    author: 'Suvuxsingh',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Constitution day LIVE broadcasting.jpg',
  ),
  'maghe-sankranti': FestivalImageCredit(
    assetPath: 'assets/images/festivals/maghe-sankranti.jpg',
    author: 'Gaurav Dhwaj Khadka',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Maghe Sankranti Food Delight.jpg',
  ),
  'ubhauli-parwa': FestivalImageCredit(
    assetPath: 'assets/images/festivals/ubhauli-parwa.jpg',
    author: 'S Pakhrin from DC, USA',
    license: 'CC BY 2.0',
    source: 'Wikimedia Commons: File:Sakela Ubhauli 2019 (48076322313).jpg',
  ),
  'gai-jatra': FestivalImageCredit(
    assetPath: 'assets/images/festivals/gai-jatra.jpg',
    author: 'Subbik',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons: File:Gai Jatra Festival in Silgadhi.jpg',
  ),
  'krishna-janmastami': FestivalImageCredit(
    assetPath: 'assets/images/festivals/krishna-janmastami.jpg',
    author: 'Krish Dulal',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons: File:Janmashtami 01.jpg',
  ),
  'haritalika-teej': FestivalImageCredit(
    assetPath: 'assets/images/festivals/haritalika-teej.jpg',
    author: 'Ganesh Paudel at ne.wikipedia',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons: File:Teej.jpg',
  ),
  'indra-jatra': FestivalImageCredit(
    assetPath: 'assets/images/festivals/indra-jatra.jpg',
    author: 'Wikimedman',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Start of Indra Jatra.jpg',
  ),
  'govardhan-puja-mha-puja': FestivalImageCredit(
    assetPath: 'assets/images/festivals/govardhan-puja-mha-puja.jpg',
    author: 'Acharya Aparajita, 2012. Mha Puja - Celebrating the Self!. Photography: Prashant Shrestha',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Mha puja Saiva.jpg',
  ),
  'usha-arghya': FestivalImageCredit(
    assetPath: 'assets/images/festivals/usha-arghya.jpg',
    author: 'Subhmanish',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Celebrating Chhath in Kataiya, Saptari by giving Argha to Sun God.jpg',
  ),
  'christmas-day': FestivalImageCredit(
    assetPath: 'assets/images/festivals/christmas-day.jpg',
    author: 'SandeshLamsalNepal',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:Christmas Day Celebration in Nepal 1.jpg',
  ),
  'gai-tihar': FestivalImageCredit(
    assetPath: 'assets/images/festivals/gai-tihar.jpg',
    author: 'Subarna Majhi',
    license: 'CC BY-SA 4.0',
    source: 'Wikimedia Commons: File:The Cow Worship.jpg',
  ),
  'basanta-panchami': FestivalImageCredit(
    assetPath: 'assets/images/festivals/basanta-panchami.jpg',
    author: 'Rupak das2009 at en.wikipedia',
    license: 'Public domain',
    source: 'Wikimedia Commons: File:Saraswati Puja.jpg',
  ),
  'tamu-lhosar': FestivalImageCredit(
    assetPath: 'assets/images/festivals/tamu-lhosar.jpg',
    author: 'Krish Dulal',
    license: 'CC BY-SA 3.0',
    source: 'Wikimedia Commons: File:Tamu Lhosar.jpg',
  ),
};
