/// Which layer produced an [AiInsight].
enum InsightSource {
  /// Generated by the AI backend.
  ai,

  /// Determined locally from the user's own cached data (offline fallback).
  local,

  /// Generic "keep tracking" placeholder when there is not enough data.
  placeholder,
}

/// Structured, validated AI insight returned by the backend (or a local
/// equivalent). The backend validates the raw model output before this is built.
class AiInsight {
  const AiInsight({
    required this.title,
    required this.message,
    required this.category,
    required this.priority,
    required this.action,
    required this.mood,
    required this.source,
    required this.generatedAt,
    this.promptVersion,
  });

  final String title;
  final String message;
  final String category;
  final String priority;
  final String action;

  /// happy | neutral | sad | sleepy
  final String mood;
  final InsightSource source;
  final DateTime generatedAt;
  final String? promptVersion;

  factory AiInsight.fromJson(Map<String, dynamic> json, {InsightSource? source}) {
    return AiInsight(
      title: (json['title'] as String?)?.trim().isNotEmpty == true
          ? (json['title'] as String).trim()
          : 'Smart Insight',
      message: (json['message'] as String?)?.trim() ?? '',
      category: (json['category'] as String?) ?? 'general',
      priority: (json['priority'] as String?) ?? 'low',
      action: (json['action'] as String?) ?? '',
      mood: (json['mood'] as String?) ?? 'neutral',
      source: source ?? InsightSource.ai,
      generatedAt:
          DateTime.tryParse((json['generatedAt'] as String?) ?? '') ??
          DateTime.now(),
      promptVersion: json['promptVersion'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'title': title,
      'message': message,
      'category': category,
      'priority': priority,
      'action': action,
      'mood': mood,
      'source': source.name,
      'generatedAt': generatedAt.toIso8601String(),
      'promptVersion': promptVersion,
    };
  }

  AiInsight copyWith({InsightSource? source, DateTime? generatedAt}) {
    return AiInsight(
      title: title,
      message: message,
      category: category,
      priority: priority,
      action: action,
      mood: mood,
      source: source ?? this.source,
      generatedAt: generatedAt ?? this.generatedAt,
      promptVersion: promptVersion,
    );
  }
}
