/// Which layer produced an [AiInsight].
enum InsightSource {
  /// Generated by the AI backend.
  ai,

  /// Determined locally from the user's own cached data (offline fallback).
  local,

  /// Generic "keep tracking" placeholder when there is not enough data.
  placeholder,
}

/// How a suggestion is worded.
enum InsightTone {
  /// Plain and factual.
  normal,

  /// Light, a little cheeky.
  playful,

  /// A friendly roast of a spending habit the numbers actually show.
  roast;

  static InsightTone fromName(Object? name) {
    for (final tone in InsightTone.values) {
      if (tone.name == name) return tone;
    }
    return InsightTone.normal;
  }
}

/// Structured, validated suggestion: from the AI backend (which validates the
/// raw model output before this is built) or worked out on the device from
/// the user's own records.
class AiInsight {
  const AiInsight({
    required this.title,
    required this.message,
    required this.category,
    required this.priority,
    required this.action,
    required this.mood,
    required this.source,
    required this.generatedAt,
    this.promptVersion,
    this.tone = InsightTone.normal,
    this.kind,
    this.variant,
    this.basis,
  });

  final String title;
  final String message;
  final String category;
  final String priority;
  final String action;

  /// The expression that goes with what is being said: `happy`, `proud`,
  /// `teasing`, `roasting`, `surprised`, `thinking`, ... See
  /// `FlameyExpression.forInsight`.
  final String mood;
  final InsightSource source;
  final DateTime generatedAt;
  final String? promptVersion;
  final InsightTone tone;

  /// The time window it was made for: `morning`, `weekly`, ...
  final String? kind;

  /// Which wording this is, so the same line is not shown twice running.
  final String? variant;

  /// For a suggestion worked out on the device: how its figure was reached.
  final String? basis;

  factory AiInsight.fromJson(
    Map<String, dynamic> json, {
    InsightSource? source,
  }) {
    return AiInsight(
      title: (json['title'] as String?)?.trim().isNotEmpty == true
          ? (json['title'] as String).trim()
          : 'Smart Insight',
      message: (json['message'] as String?)?.trim() ?? '',
      category: (json['category'] as String?) ?? 'general',
      priority: (json['priority'] as String?) ?? 'low',
      action: (json['action'] as String?) ?? '',
      mood: (json['mood'] as String?) ?? 'neutral',
      source:
          source ??
          InsightSource.values.firstWhere(
            (value) => value.name == json['source'],
            orElse: () => InsightSource.ai,
          ),
      generatedAt:
          DateTime.tryParse((json['generatedAt'] as String?) ?? '') ??
          DateTime.now(),
      promptVersion: json['promptVersion'] as String?,
      tone: InsightTone.fromName(json['tone']),
      kind: json['kind'] as String?,
      variant: json['variant'] as String?,
      basis: json['basis'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'title': title,
      'message': message,
      'category': category,
      'priority': priority,
      'action': action,
      'mood': mood,
      'source': source.name,
      'generatedAt': generatedAt.toIso8601String(),
      'promptVersion': promptVersion,
      'tone': tone.name,
      'kind': kind,
      'variant': variant,
      'basis': basis,
    };
  }

  AiInsight copyWith({
    InsightSource? source,
    DateTime? generatedAt,
    String? kind,
  }) {
    return AiInsight(
      title: title,
      message: message,
      category: category,
      priority: priority,
      action: action,
      mood: mood,
      source: source ?? this.source,
      generatedAt: generatedAt ?? this.generatedAt,
      promptVersion: promptVersion,
      tone: tone,
      kind: kind ?? this.kind,
      variant: variant,
      basis: basis,
    );
  }
}
