param()

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Web

$dir = "assets\images\festivals"
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

# festival id -> Commons file title
$map = [ordered]@{
  'buddha-jayanti'   = 'File:Buddha Jayanti-IMG 9085.jpg'
  'janai-purnima'    = 'File:Boys ablution Janai Purnima.jpg'
  'vijaya-dashami'   = 'File:Soaring High in Dashain.jpg'
  'laxmi-puja'       = 'File:Laxmi Puja.jpg'
  'kukur-tihar'      = 'File:Kukur Tihar or Dog Puja in Kathmandu. Dog decorate with marigold garland and Tika.jpg'
  'bhai-tika'        = 'File:Bhai Tika, Bhai Tika.jpg'
  'chhath'           = 'File:Chhath festival in Nepal-070A2127.jpg'
  'holi'             = 'File:Holi festival celebration in Kathmandu 2025-070A3156.jpg'
  'nepali-new-year'  = 'File:Bisket Jatra festival 2018 at the Nyatapola temple, Bhaktapur.jpg'
  'constitution-day' = 'File:Constitution day LIVE broadcasting.jpg'
  'maghe-sankranti'  = 'File:Maghe Sankranti Food Delight.jpg'
  'ubhauli-parwa'    = 'File:Sakela Ubhauli 2019 (48076322313).jpg'
  'gai-jatra'        = 'File:Gai Jatra Festival in Silgadhi.jpg'
  'krishna-janmastami' = 'File:Janmashtami 01.jpg'
  'haritalika-teej'  = 'File:Teej.jpg'
  'indra-jatra'      = 'File:Start of Indra Jatra.jpg'
  'govardhan-puja-mha-puja' = 'File:Mha puja Saiva.jpg'
  'usha-arghya'      = 'File:Celebrating Chhath in Kataiya, Saptari by giving Argha to Sun God.jpg'
  'christmas-day'    = 'File:Christmas Day Celebration in Nepal 1.jpg'
  'gai-tihar'        = 'File:The Cow Worship.jpg'
  'basanta-panchami' = 'File:Saraswati Puja.jpg'
  'tamu-lhosar'      = 'File:Tamu Lhosar.jpg'
}

$rows = @()

$ua = 'KharchaAppBot/1.0 (personal app; contact nischalpandey.dev@gmail.com)'

function Invoke-WithRetry {
  param([scriptblock]$ScriptBlock)
  for ($i = 0; $i -lt 4; $i++) {
    try { return & $ScriptBlock }
    catch {
      if ("$($_.Exception.Message)" -match '429') { Start-Sleep -Seconds 20 } else { throw }
    }
  }
  throw 'Gave up after retries.'
}

foreach ($id in $map.Keys) {
  $title = $map[$id]
  $q = [uri]::EscapeDataString($title)
  $url = "https://commons.wikimedia.org/w/api.php?action=query&format=json&titles=$q&prop=imageinfo&iiprop=url|extmetadata&iiurlwidth=1000&maxlag=5"
  Start-Sleep -Seconds 6
  try {
    $r = Invoke-WithRetry { Invoke-RestMethod -Uri $url -UseBasicParsing -TimeoutSec 40 -UserAgent $ua }
    $page = $r.query.pages.PSObject.Properties.Value | Select-Object -First 1
    $ii = $page.imageinfo[0]
    $em = $ii.extmetadata

    $thumb = if ($ii.thumburl) { $ii.thumburl } else { $ii.url }
    $lic = $em.LicenseShortName.value
    $artistHtml = $em.Artist.value
    if ($artistHtml) {
      $stripped = $artistHtml -replace '<[^>]+>', ' '
      $stripped = $stripped -replace '&nbsp;', ' '
      $stripped = $stripped -replace '\s+', ' '
      $artist = [System.Web.HttpUtility]::HtmlDecode($stripped).Trim()
    } else {
      $artist = 'Unknown author'
    }

    $ext = '.jpg'
    $pathOnly = ($thumb -split '\?')[0]
    if ($pathOnly -match '\.(jpg|jpeg|png)$') { $ext = '.' + $Matches[1].ToLower() }
    $out = Join-Path $dir "$id$ext"

    if (-not (Test-Path $out)) {
      Invoke-WithRetry { Invoke-WebRequest -Uri $thumb -OutFile $out -UseBasicParsing -TimeoutSec 90 -UserAgent $ua }
    }
    $kb = [math]::Round((Get-Item $out).Length / 1KB, 1)
    "OK  $id -> $out (${kb} KB, $lic)"

    $rows += [pscustomobject]@{
      Id      = $id
      File    = "assets/images/festivals/$id$ext"
      License = $lic
      Artist  = $artist
      Title   = $title
    }
  } catch {
    "FAIL $id : $($_.Exception.Message)"
  }
}

"---- generating credits ----"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// GENERATED by tool/fetch_festival_images.ps1 - do not edit by hand.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('// Every photograph below is a real, freely licensed image of the festival it is')
[void]$sb.AppendLine('// attached to, downloaded from Wikimedia Commons. Festivals with no suitable')
[void]$sb.AppendLine('// photograph are deliberately left without one so the UI shows its own icon')
[void]$sb.AppendLine('// instead of an unrelated picture.')
[void]$sb.AppendLine('class FestivalImageCredit {')
[void]$sb.AppendLine('  const FestivalImageCredit({')
[void]$sb.AppendLine('    required this.assetPath,')
[void]$sb.AppendLine('    required this.author,')
[void]$sb.AppendLine('    required this.license,')
[void]$sb.AppendLine('    required this.source,')
[void]$sb.AppendLine('  });')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('  final String assetPath;')
[void]$sb.AppendLine('  final String author;')
[void]$sb.AppendLine('  final String license;')
[void]$sb.AppendLine('  final String source;')
[void]$sb.AppendLine('}')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('const Map<String, FestivalImageCredit> festivalImageCredits =')
[void]$sb.AppendLine('    <String, FestivalImageCredit>{')
foreach ($r in $rows) {
  $a = $r.Artist -replace "'", "\'"
  $t = $r.Title -replace "'", "\'"
  $f = $r.File -replace "'", "\'"
  [void]$sb.AppendLine("  '$($r.Id)': FestivalImageCredit(")
  [void]$sb.AppendLine("    assetPath: '$f',")
  [void]$sb.AppendLine("    author: '$a',")
  [void]$sb.AppendLine("    license: '$($r.License)',")
  [void]$sb.AppendLine("    source: 'Wikimedia Commons: $t',")
  [void]$sb.AppendLine("  ),")
}
[void]$sb.AppendLine('};')

$outFile = 'lib\data\festival_image_credits.g.dart'
$outDir = Split-Path $outFile
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
"wrote $outFile with $($rows.Count) credits"
